from final_project_classes import Utils, anova_lm

visualization_methods = ["Show dataset", "Scatter plot 2 columns",
                         "Scatter plot of variable by levels", "Histogram",
                         "Histogram of variable by levels"]
all_tests = ["Permutation test",
             "t-test between columns", "t-test by level", "One way ANOVA",
             "Two way ANOVA", "Repeated Measures ANOVA", "Mann-Whitney test between columns",
             "Mann-Whitney test by level", "Linear regression",
             "Spearman correlation", "Pearson correlation", "Chi squared for independence"]

correct_tests_dict = {"Mann Whitney": ["Mann-Whitney test by level", "Mann-Whitney test between columns",
                                       "t-test by level", "t-test between columns"],
                      'independent samples t-test': ["t-test by column", "t-test by level",
                                                     "Mann-Whitney test by level"],
                      'paired t-test': ["t-test by level", "t-test by column"],
                      "Spearman correlation": ["Spearman correlation"],
                      'Pearson correlation': ["Linear regression", "Pearson correlation",
                                              "Spearman correlation"],
                      'Regression': ["Linear regression", "Pearson correlation", "Spearman correlation"],
                      'Repeated Measures ANOVA': ["Repeated Measures ANOVA"],
                      'ANOVA 1-way': ["One way ANOVA"],
                      'ANOVA 2-way': ["Two way ANOVA"],
                      'Chi squared': ["Chi squared for independence"]}

incorrect_effect_sizes = {
    "Mann Whitney": ["Cohen's d between columns", "Eta squared for one-way ANOVA",
                     "Eta squared for two-way ANOVA",
                     "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                     "r squared for linear regression", "r squared for spearman correlation"],
    'independent samples t-test': ["Cohen's d between columns", "Eta squared for one-way ANOVA",
                                   "Eta squared for two-way ANOVA",
                                   "Eta squared for Repeated Measures ANOVA",
                                   "r squared for pearson correlation",
                                   "r squared for linear regression", "r squared for spearman correlation"],
    'paired t-test': ["Cohen's d between columns", "Eta squared for one-way ANOVA",
                      "Eta squared for two-way ANOVA",
                      "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                      "r squared for linear regression", "r squared for spearman correlation"],
    "Spearman correlation": ["Cohen's d between columns", "Cohen's d by level",
                             "Eta squared for one-way ANOVA", "Eta squared for two-way ANOVA",
                             "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                             "r squared for linear regression"],
    'Pearson correlation': ["Cohen's d between columns", "Cohen's d by level",
                            "Eta squared for one-way ANOVA", "Eta squared for two-way ANOVA",
                            "Eta squared for Repeated Measures ANOVA", "r squared for spearman correlation"],
    'Regression': ["Cohen's d between columns", "Cohen's d by level",
                   "Eta squared for one-way ANOVA", "Eta squared for two-way ANOVA",
                   "Eta squared for Repeated Measures ANOVA", "r squared for spearman correlation"],
    'Repeated Measures ANOVA': ["Cohen's d between columns", "Cohen's d by level",
                                "Eta squared for one-way ANOVA", "Eta squared for two-way ANOVA",
                                "r squared for pearson correlation",
                                "r squared for linear regression", "r squared for spearman correlation"],
    'ANOVA 1-way': ["Cohen's d between columns", "Cohen's d by level",
                    "Eta squared for two-way ANOVA",
                    "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                    "r squared for linear regression", "r squared for spearman correlation"],
    'ANOVA 2-way': ["Cohen's d between columns", "Cohen's d by level",
                    "Eta squared for one-way ANOVA",
                    "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                    "r squared for linear regression", "r squared for spearman correlation"],
    'Chi squared': ["Cohen's d between columns", "Cohen's d by level",
                    "Eta squared for one-way ANOVA", "Eta squared for two-way ANOVA",
                    "Eta squared for Repeated Measures ANOVA", "r squared for pearson correlation",
                    "r squared for linear regression", "r squared for spearman correlation"]}

valid_validity_tests_dict = {
    "Mann Whitney": ["Bootstrap", "Permutation test"],
    'independent samples t-test': ["Bootstrap", "Permutation test", "Cohen's d by level", "Cohen's d between columns"],
    'paired t-test': ["Bootstrap", "Permutation test", "Cohen's d by level", "Cohen's d between columns"],
    "Spearman correlation": ["Bootstrap", "Permutation test", "r squared for pearson correlation"],
    'Pearson correlation': ["Bootstrap", "Permutation test", "r squared for pearson correlation",
                            "r squared for linear regression", "r squared for spearman correlation"],
    'Regression': ["Bootstrap", "Permutation test", "r squared for pearson correlation",
                   "r squared for linear regression", "r squared for spearman correlation"],
    'Repeated Measures ANOVA': ["Bootstrap", "Permutation test", "Eta squared for Repeated Measures ANOVA"],
    'ANOVA 1-way': ["Bootstrap", "Permutation test", "Eta squared for one-way ANOVA"],
    'ANOVA 2-way': ["Bootstrap", "Permutation test", "Eta squared for two-way ANOVA"],
    'Chi squared': ["Bootstrap", "Permutation test"]}

test_args_dict = {"t-test between columns": ["col1", "col2", "method", "alternative"],
                  "t-test by level": ["col1", "col2", "col2_val1", "col2_val2", "method", "alternative"],
                  "One way ANOVA": ["dependent_var", "factor"],
                  "Two way ANOVA": ["dependent_var", "factor1", "factor2"],
                  "Repeated Measures ANOVA": ["dependent_var", "subject", "factor"],
                  "Mann-Whitney test between columns": ["col1", "col2", "alternative"],
                  "Mann-Whitney test by level": ["col1", "col2", "col2_val1", "col2_val2", "alternative"],
                  "Linear regression": ["col1", "col2"],
                  "Spearman correlation": ["col1", "col2"],
                  "Pearson correlation": ["col1", "col2"],
                  "Chi squared for independence": ["col1", "col2"]}
test_func_getters_dict = {"t-test between columns": Utils.get_column_ttest_func,
                          "t-test by level": Utils.get_t_test_func,
                          "One way ANOVA": lambda **kwargs: lambda df, kwargs=kwargs: anova_lm(
                              Utils.get_one_way_anova_model(**kwargs)),
                          "Two way ANOVA": lambda **kwargs: lambda df, kwargs=kwargs: anova_lm(
                              Utils.get_two_way_anova_model(**kwargs)),
                          "Repeated Measures ANOVA": lambda **kwargs: lambda df,
                                                                             kwargs=kwargs: Utils.get_rm_anova_model(
                              **kwargs).anova_table,
                          "Mann-Whitney test between columns": Utils.get_column_mann_whitney_func,
                          "Mann-Whitney test by level": Utils.get_mann_whitney_func,
                          "Linear regression": Utils.get_regress_func,
                          "Spearman correlation": Utils.get_spearman_correlation_func,
                          "Pearson correlation": Utils.get_pearson_correlation_func,
                          "Chi squared for independence": Utils.get_chi_for_indep_func}
log_dict = {"name": None, "group": None, "id": None, "q_idx": None, "question_grade": None,
            "question": None, "q_type": None, "outliers": None, "variables": None,
            "reported_methods": None, "reported_test": None,
            "reported_validity": None, "methods_visualizations": None,
            "methods_contain_correct_test": None, "methods_incorrect_test": None,
            "methods_contain_incorrect_effect_size": None,
            "methods_contain_correct_test_but_wrong_setting": None,
            "methods_multiple_hypothesis_testing": None,
            "test_report_coherent_with_test_chosen_in_methods": None,
            "test_report_values_are_correct": None,
            "is_valid_conclusion_coherent_with_a_parametric_tests": None,
            'a_parametric_tests_validity': None, "is_valid_conclusion_contains_irrelevant_tests": False,
            'valid_conclusion_irrelevant_tests': None, "free_text": None}
check_dict = {"methods_contain_visualization": False,
              "methods_contain_correct_test": False,
              "methods_contain_incorrect_test": False,
              "methods_contain_incorrect_effect_size": False,
              "methods_contain_correct_test_but_wrong_setting": False,
              "methods_contain_multiple_hypothesis_testing": False,
              "test_report_coherent_with_test_chosen_in_methods": False,
              "test_report_values_are_correct": False,
              "is_valid_conclusion_coherent_with_a_parametric_tests": False,
              "is_valid_conclusion_contains_irrelevant_tests": False}
scoring_dict = {"methods_contain_visualization": 2,
                "methods_contain_correct_test": 10,
                "methods_contain_incorrect_test": -2,
                "methods_contain_incorrect_effect_size": -2,
                "methods_contain_correct_test_but_wrong_setting": -5,
                "methods_contain_multiple_hypothesis_testing": -2,
                "test_report_coherent_with_test_chosen_in_methods": 5,
                "test_report_values_are_correct": 1,
                "is_valid_conclusion_coherent_with_a_parametric_tests": 2,
                "is_valid_conclusion_contains_irrelevant_tests": -2}

aparametric_tests = ["Permutation test", "Chi squared for independence", "Spearman correlation",
                     "Mann-Whitney test by level", "Mann-Whitney test between columns"]

hypothesis_direction_to_ttest_hypothesis_dict = {1: "greater", -1: "less", 0: "two-sided"}
